NUM_OF_STREAMS = 1

MAX_BUFFER_SIZE = 5
BUFFER_REDUCTION = 2


WIDTH = 640
HEIGHT = 480
SEND_COMMAND = ''
FRAMERATE = 30
ICE_PUBLISHING_ADDRESS = ''
ICE_PUBLISHING_PORT = ''
ICE_SUBSCRIBING_ADDRESS_TABLE = ''
ICE_SUBSCRIBING_ADDRESS_SCENE = ''
IMAGE_TYPE = ''
VIDEO_FILE = ''
THREADS = 2
N_CLIPS = 0
N_CLIP_FRAMES = 0
N_SKIPPED_FRAMES = 0
TIME_WINDOW = 0
ESTIMATION_STEP_TIME = 0
VERBOSE = False
DISPLAY = False
DEVICE_HELP = None
DEVICE_MASKRCNN = 0
